spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost}:1433;databaseName=cakies;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Cakies@12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
        use_nationalized_character_data: true
  sql:
    init:
      mode: never
      encoding: UTF-8

server:
  port: 8080
