spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost}:1433;databaseName=cakies;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Cakies@12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

server:
  port: 8080
